name: Docker Image Sample

on:
  workflow_dispatch:
    inputs:
      image_name: 
         type: choice
         description: pick image to be pushed
         options:
         - image_1
         - image_ah
      tag_name:
        description: What is the tag
        type: boolean
        default:  true 
jobs:
   
   today_job:
         if: github.event.inputs.tag_name  == 'true'  
         runs-on: [ gh_label ]
         steps:
            - run: echo "Hello"
