name: Generate Timestamp File and Upload Artifact

on:
  workflow_dispatch:
   
jobs:
  generate-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Timestamp
        run: |
          echo "Generating timestamp..."
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          echo "$TIMESTAMP" > timestamp.txt
      - name: Upload timestamp file
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt
        if: always()
