name: Generate Timestamp

on:
  workflow_dispatch:
jobs:
  generate-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Timestamp
        run: echo $(date +%s) > timestamp.txt
      - name: Upload Timestamp
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt
     
  display:
    runs-on: ubuntu-latest
    needs: generate-timestamp
    steps:
      - name: Download number file
        uses: actions/download-artifact@v2
        with:
          name: number
      - name: Display badge
        uses: shieldsio/shields@v5.2.0
        with:
          label: Number
          message: ${{ steps.download.outputs.artifact }}
          color: blue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
