name: Generate Timestamp

on:
  workflow_dispatch:
jobs:
  generate-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Timestamp
        run: echo $(date +%s) > timestamp.txt
      - name: Upload Timestamp
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt
      - name: Commit Timestamp File
        run: |
          git config --local user.email "harshinikamaraj24@gmail.com"
          git config --local user.name "Harshini-24-IT"
          git add timestamp.txt
          git commit -m "Add timestamp.txt file"
          git push
