name: Docker Image Sample

on:
  workflow_dispatch:
   
jobs:
   
   today_job:
         runs-on: [ new_run ]
         steps:
            - run: echo "Hello"
   new_job:
      runs-on: [ new_run ]
      needs: [ today_job ]
      steps:
      - name: Generate file with timestamp
        run: |
             $content = "Timestamp: $(Get-Date)"
             Set-Content -Path timestamp.txt -Value $content
            
 
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: timestamp-report
          path: src/timestamp.txt
 
  
