name: Generate Timestamp

on:
  workflow_dispatch:
jobs:
  generate-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Timestamp
        run: echo $(date +%s) > timestamp.txt
      - name: Upload Timestamp
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt
     
  display:
     runs-on: ubuntu-latest
     needs: generate-timestamp
     steps:
      - name: Download number file
        uses: actions/download-artifact@v2
        with:
          name: number
      - name: Display badge
        uses: badges/gh-actions@v1.0.0
        with:
          args: |
            badge.svg?label=Number&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAABwUlEQVR4nO3Uv0vUQBBA4U9FyU0pEZUv4AkLkIWSxEJd4Z1C4YvQlaBxWgWy0hSFAiSFFB4IQUgrwRKUE8ZSHB4C4YLYMvI2MDx+8Hm+z5ySd7rvv3+nn3f5iZ2/3f97J+6n9zF8aAYyBiCGJgiSYgRiMYhiYIYmCJJiBGIxhY7+P3zB/sV7Bfq+Qfb+J+E1Hv9XWz5PpfoS/YCfyz7ovv5Gbywvu8z4ft4iuf86Qv72X9Wfj/m+Cf/1f/2j19uLZ/05T7Ys0sUUPV6Ntw9y0sV1gOzlj0mxyFpBHxazkEKfO41oHHbjE3ECqOMm9lWf23drvpGnemVjvt2bnZheuT7TfYsYsV6jK9yUuFbUyzHuxKjMZdsykcsZLg79oz/ZkMjK3Yq3fJ9XnnsQ2W2dHap43k3tq1jGv2mOwI07Hl1a5f9Xjv5+/WmS0kMVGk+bnnx/PZv1/jei4/+F0Py63DdP9+tXj0WudS5NbS7ujS5zbHTvF8ZJaKcc4e4jlzGmtXybk55KjLWzVu09XL3q3rbZPVvTX8QwWz5R5I5L5y9v5+f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5fn/wGKfwbN/QLoAAAAASUVORK5CYII=&color=blue&style=flat-square&logoColor=white
          link: https://github.com/username/repo
          env:
            GITHUB_TOKEN
