name: Docker Image Sample

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: What is the tag
        type: boolean
        default:  true 
jobs:
   
   today_job:
         if: github.event.inputs.tag_name  == 'false'  
         runs-on: [ new_run  ]
         steps:
           -  run: echo "Hello"
