name: Generate Timestamp

on:
  workflow_dispatch:
jobs:
  generate-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Timestamp
        run: echo $(date +%s) > timestamp.txt
      - name: Upload Timestamp
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt
     
  display:
    runs-on: ubuntu-latest
    needs: generate-timestamp
    steps:
      - name: Download number file
        uses: actions/download-artifact@v2
        with:
          name: number
      - name: Generate badge URL
        run: echo "::set-output name=badge_url::https://img.shields.io/badge/Number-${{ steps.number.outputs.number }}-blue?style=flat-square"
        id: badge
      - name: Update README file
        uses: maxkomarychev/octions/update-readme@0.2.2
        with:
          readme-path: README.md
          replace-pattern: '(<badge>)(.*?)(<\/badge>)'
          replace-with: '<badge>[![Number](${{ steps.badge.outputs.badge_url }})](https://github.com/username/repo)</badge>'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
