name: Generate Timestamp File and Upload Artifact

on:
  workflow_dispatch:
   
jobs:
  generate-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Timestamp File
        run: |
              echo "Generating timestamp..."
              TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
              echo "::set-output name=timestamp::$TIMESTAMP"
        # Save the timestamp as an output variable
        # so it can be used in other steps or jobs
      
          
      - name: Upload Timestamp Artifact
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt
