name: Generate Timestamp

on:
  workflow_dispatch:
jobs:
  generate-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Timestamp
        run: echo $(date +%s) > timestamp.txt
      - name: Upload Timestamp
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt
