name: Generate Timestamp and Badge

on:
  workflow_dispatch:

jobs:
  Installation:
    runs-on: ubuntu-latest
    steps:
    - name: Add /usr/local/bin to PATH
      run: |
       echo "::add-path::/usr/local/bin"

    - name: Install badgen
      run: npm install -g badgen
    - name: Add badgen to PATH
      run: echo "::add-path::/usr/local/bin"

  generate-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Timestamp
        run: echo $(date +%s) > timestamp.txt

      - name: Install Badgen
        run: npm install -g badgen

      - name: Generate Badge
        run: badgen "Timestamp:$(cat timestamp.txt)" --style=flat-square --color=blue > badge.svg

      - name: Add Badge to README
        run: |
          echo "" >> README.md
          echo "![Timestamp](badge.svg)" >> README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update timestamp badge"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
