name: Update Badge
on:
  workflow_dispatch:
jobs:
  generate_timestamp:
     runs-on: [ubuntu-latest]
     
     steps:
     - uses: actions/checkout@v3
     - name: generate workflow file
       run: |
             $content = "Timestamp: $(Get-Date)"
             Set-Content -Path timestamp.txt -Value $content
     - name: Upload artifact
       uses: actions/upload-artifact@v2
       with:
          name: timestamp-report
          path: timestamp.txt  
     
